FROM node:lts-buster AS builder
WORKDIR /app
COPY ./angular/package.json ./angular/yarn.lock /app/
RUN yarn
COPY ./angular /app/
RUN yarn build:prod
# CMD yarn start --prod

FROM nginx
COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./config/nginx.conf /etc/nginx/conf.d/default.conf
